version: "3"
services:
  client:
    build: ./client
    ports:
      - 5010:5010
    depends_on:
      - server
      - db
  server:
    build: ./server
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - /pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: server
      POSTGRES_USER: server

